name: postbook_v2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  animated_notch_bottom_bar: ^1.0.3
  bloc: ^8.1.4
  cherry_toast: ^1.10.1
  faker: ^2.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  http: ^1.2.1
  meta: ^1.11.0
  random_avatar: ^0.0.8
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
